# Site settings
title: MLH Hackcon
description: >
  Hackcon is the hackathon orgnaizers' conference.
url: "http://hackcon.io"
twitter_username: mlhacks
github_username:  mlh

# Build settings
markdown: kramdown
